apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-17T02:12:30Z"
  generation: 3
  labels:
    app: test1
  name: test1
  namespace: default
  resourceVersion: "4790"
  selfLink: /apis/apps/v1/namespaces/default/deployments/test1
  uid: 15afaee0-67ef-4bdf-ae68-24bca5a63024
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test1
    spec:
      containers:
      - image: gcr.io/ccgroup6project/test1:v1
        imagePullPolicy: IfNotPresent
        name: test1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-17T02:13:32Z"
    lastUpdateTime: "2020-11-17T02:13:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-11-17T02:12:30Z"
    lastUpdateTime: "2020-11-17T02:13:32Z"
    message: ReplicaSet "test1-7bdc6c566c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
