apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test1
  name: test1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - image: gcr.io/ccgroup6project/github.com/dathanki/cloudcomputingg6
          imagePullPolicy: IfNotPresent
          name: test1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test1
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test1
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: test1
  name: test1-service
  namespace: default
spec:
  clusterIP: 10.35.244.61
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30528
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: test1
  sessionAffinity: None
  type: LoadBalancer
